language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install git gcc gfortran python-dev libopenblas-dev liblapack-dev cython
  - git clone https://github.com/numpy/numpy.git
  - git clone https://github.com/scipy/scipy.git
script: pytest
