language: python

before_install:
  - sudo apt-get update
  - sudo apt-get install git gcc gfortran python-dev libopenblas-dev liblapack-dev cython
  - git clone https://github.com/numpy/numpy.git
  - git clone https://github.com/scipy/scipy.git
  - pip install -r requirements.txt
install:
  - cd numpy
  - python setup.py build
  - python setup.py install
  - cd ../scipy
  - python setup.py build
  - python setup.py install
  - cd ..
script:
  - python numpy_tests.py
  - python scipy_tests.py
